### ISSUE TITLE
Fallo por falta de método

### ISSUE THREAD

**Issue by penicolas** [penicolas/clibooks#10]
Traceback (most recent call last):
  File "C:\Python35\Scripts\clibooks-script.py", line 11, in <module>
    load_entry_point('clibooks', 'console_scripts', 'clibooks')()
  File "d:\users\pnicolas\code\github\clibooks\clibooks\clibooks.py", line 96, in main
    mybooks.add(options.add_isbn13[0])
  File "d:\users\pnicolas\code\github\clibooks\clibooks\books.py", line 129, in add
    if book.get_OL_info():
  File "d:\users\pnicolas\code\github\clibooks\clibooks\books.py", line 86, in get_OL_info
    self.isbn10 = isbn.to_isbn10(self.isbn13)
AttributeError: module 'clibooks.isbn' has no attribute 'to_isbn10'

**Comment by penicolas** [comment]
No es posible pasar un ISBN13 a ISBN10 de manera única, por lo tanto elimino la referencia a dicho método.
