### ISSUE TITLE
Fail extract books to Markdown

### ISSUE THREAD

**Issue by penicolas** [penicolas/clibooks#8]
Fail extract books to Markdown:

```
$ clibooks --markdown
Traceback (most recent call last):
  File "C:\Python35\Scripts\clibooks-script.py", line 11, in <module>
    load_entry_point('clibooks', 'console_scripts', 'clibooks')()
  File "d:\users\pnicolas\code\github\clibooks\clibooks\clibooks.py", line 72, in main
    mybooks.tomarkdown()
AttributeError: 'Books' object has no attribute 'tomarkdown'
```

**Comment by penicolas** [comment]
Ideas:
- Que `--markdown` sea una opción para los tipo listado
- Que podamos indicar en el fichero de configuración el formato del `markdown`
